<map version="freeplane 1.11.1">
<!--To view this file, download free mind mapping software Freeplane from https://www.freeplane.org -->
<node TEXT="ЗАЩИТА ИНФОРМАЦИИ&#xa;ОБЪЕКТ ИНФОРМАТИЗАЦИИ.&#xa;ФАКТОРЫ, ВОЗДЕЙСТВУЮЩИЕ НА ИНФОРМАЦИЮ" LOCALIZED_STYLE_REF="AutomaticLayout.level.root" FOLDED="false" ID="ID_1090958577" CREATED="1409300609620" MODIFIED="1685029207021" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt" SHAPE_HORIZONTAL_MARGIN_QUANTITY="10 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="10 pt">
<font NAME="SansSerif" SIZE="18" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<hook NAME="accessories/plugins/AutomaticLayout.properties" VALUE="ALL"/>
<hook NAME="MapStyle" background="#000066" zoom="0.63">
    <properties show_icon_for_attributes="true" edgeColorConfiguration="#808080ff,#ff0000ff,#0000ffff,#00ff00ff,#ff00ffff,#00ffffff,#7c0000ff,#00007cff,#007c00ff,#7c007cff,#007c7cff,#7c7c00ff" show_note_icons="true" associatedTemplateLocation="template:/light_solarized_template.mm" fit_to_viewport="false"/>

<map_styles>
<stylenode LOCALIZED_TEXT="styles.root_node" STYLE="oval" UNIFORM_SHAPE="true" VGAP_QUANTITY="24 pt">
<font SIZE="24"/>
<stylenode LOCALIZED_TEXT="styles.predefined" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="default" ID="ID_271890427" ICON_SIZE="12 pt" COLOR="#000000" STYLE="fork">
<arrowlink SHAPE="CUBIC_CURVE" COLOR="#000000" WIDTH="2" TRANSPARENCY="200" DASH="" FONT_SIZE="9" FONT_FAMILY="SansSerif" DESTINATION="ID_271890427" STARTARROW="NONE" ENDARROW="DEFAULT"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" ITALIC="false"/>
<richcontent CONTENT-TYPE="plain/auto" TYPE="DETAILS"/>
<richcontent TYPE="NOTE" CONTENT-TYPE="plain/auto"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.details"/>
<stylenode LOCALIZED_TEXT="defaultstyle.attributes">
<font SIZE="9"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.note" COLOR="#000000" BACKGROUND_COLOR="#ffffff" TEXT_ALIGN="LEFT"/>
<stylenode LOCALIZED_TEXT="defaultstyle.floating">
<edge STYLE="hide_edge"/>
<cloud COLOR="#f0f0f0" SHAPE="ROUND_RECT"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.selection" BACKGROUND_COLOR="#afd3f7" BORDER_COLOR_LIKE_EDGE="false" BORDER_COLOR="#afd3f7"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.user-defined" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="styles.topic" COLOR="#18898b" STYLE="fork">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subtopic" COLOR="#cc3300" STYLE="fork">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subsubtopic" COLOR="#669900">
<font NAME="Liberation Sans" SIZE="10" BOLD="true"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.important" ID="ID_67550811">
<icon BUILTIN="yes"/>
<arrowlink COLOR="#003399" TRANSPARENCY="255" DESTINATION="ID_67550811"/>
</stylenode>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.AutomaticLayout" POSITION="bottom_or_right" STYLE="bubble">
<stylenode LOCALIZED_TEXT="AutomaticLayout.level.root" COLOR="#000000" STYLE="oval" SHAPE_HORIZONTAL_MARGIN="10 pt" SHAPE_VERTICAL_MARGIN="10 pt">
<font SIZE="18"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,1" COLOR="#0033ff">
<font SIZE="16"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,2" COLOR="#00b439">
<font SIZE="14"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,3" COLOR="#990000">
<font SIZE="12"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,4" COLOR="#111111">
<font SIZE="10"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,5"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,6"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,7"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,8"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,9"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,10"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,11"/>
</stylenode>
</stylenode>
</map_styles>
</hook>
<node TEXT="Термины и определения" LOCALIZED_STYLE_REF="AutomaticLayout.level,1" POSITION="top_or_left" ID="ID_1227674445" CREATED="1684937230752" MODIFIED="1685029207022" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" HGAP_QUANTITY="-219.99999 pt" VSHIFT_QUANTITY="38.25 pt">
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<node TEXT="Объект информатизации" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1604169854" CREATED="1684937757031" MODIFIED="1685029207022" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" HGAP_QUANTITY="61.25 pt">
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Система обработки информации" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1332552412" CREATED="1684938672349" MODIFIED="1685029207023" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" HGAP_QUANTITY="36.5 pt">
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Побочное электромагнитное излучение" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_541312241" CREATED="1684938720628" MODIFIED="1685029207023" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Паразитное электромагнитное излучение" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1032368804" CREATED="1684938796770" MODIFIED="1685029207024" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Наведенный в токопроводящих линейных элементах технических средств сигнал" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_421263634" CREATED="1684938831014" MODIFIED="1685029207024" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt">
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Закладочное средство [устройство]" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_452793183" CREATED="1684938904586" MODIFIED="1685029207024" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" HGAP_QUANTITY="35.75 pt">
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Программная закладка" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1278455064" CREATED="1685025332273" MODIFIED="1685029207024" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="71 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Недекларированные возможности (программного обеспечения)" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_973124457" CREATED="1685025357290" MODIFIED="1685029207024" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" VSHIFT_QUANTITY="-3 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Остаточный риск" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_558494656" CREATED="1685025379701" MODIFIED="1685029207025" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="83.75 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Вредоносная программа" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1463431300" CREATED="1685025393891" MODIFIED="1685029207025" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="62 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="(Компьютерный) Вирус" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1930600792" CREATED="1685025402129" MODIFIED="1685029207025" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="64.25 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Компьютерная атака" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1145674187" CREATED="1685025479374" MODIFIED="1685029207025" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="74 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Сетевая атака" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1593777492" CREATED="1685025479374" MODIFIED="1685029207025" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="100.25 pt">
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
</node>
<node TEXT="Программное воздействие" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_407896507" CREATED="1685025479374" MODIFIED="1685029207025" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="16 px" SHAPE_VERTICAL_MARGIN="10 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="56 pt">
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
</node>
</node>
<node TEXT="Нормативные ссылки" LOCALIZED_STYLE_REF="AutomaticLayout.level,1" POSITION="bottom_or_right" ID="ID_1036059494" CREATED="1685025774332" MODIFIED="1685029241478" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-768.24998 pt" VSHIFT_QUANTITY="53.25 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<node TEXT="ГОСТ Р 50922" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1065602521" CREATED="1685025877142" MODIFIED="1685029207025" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-226.74999 pt" VSHIFT_QUANTITY="-2.25 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
</node>
<node TEXT="Область применения" LOCALIZED_STYLE_REF="AutomaticLayout.level,1" POSITION="bottom_or_right" ID="ID_1811472774" CREATED="1685025787128" MODIFIED="1685029261081" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-504.24998 pt" VSHIFT_QUANTITY="111 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Основные положения" LOCALIZED_STYLE_REF="AutomaticLayout.level,1" POSITION="top_or_left" ID="ID_80200081" CREATED="1685026710978" MODIFIED="1685029300648" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-821.49998 pt" VSHIFT_QUANTITY="-13.5 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Классификация факторов, воздействующих на безопасность&#xa;защищаемой информации" LOCALIZED_STYLE_REF="AutomaticLayout.level,1" POSITION="bottom_or_right" ID="ID_192348357" CREATED="1685026754912" MODIFIED="1685029277613" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-184.74999 pt" VSHIFT_QUANTITY="-106.5 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<node TEXT="Факторы, воздействующие или могущие воздействовать на безопасность защищаемой ин&#xa;формации и подлежащие учету при организации защиты информации, по признаку отношения к при&#xa;роде возникновения подразделяют на классы:&#xa;- объективные;&#xa;- субъективные." LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1466604072" CREATED="1685026931314" MODIFIED="1685029207026" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="По отношению к ОИ факторы, воздействующие на безопасность защищаемой информации,&#xa;подразделяют на внутренние и внешние." LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_1671370631" CREATED="1685026943843" MODIFIED="1685029207027" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Факторы, воздействующие на защищаемую информацию, в соответствии с признаками клас&#xa;сификации подразделяют на:&#xa;- подклассы;&#xa;- группы;&#xa;- подгруппы;&#xa;- виды;&#xa;- подвиды." LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_406732899" CREATED="1685026960323" MODIFIED="1685029207028" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
</node>
<node TEXT="Перечень объективных и субъективных факторов, воздействующих&#xa;на безопасность защищаемой информации" LOCALIZED_STYLE_REF="AutomaticLayout.level,1" POSITION="top_or_left" ID="ID_1193334585" CREATED="1685026998672" MODIFIED="1685029207028" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-249.24999 pt" VSHIFT_QUANTITY="24.75 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<node TEXT="Перечень объективных факторов, воздействующих на безопасность защищаемой&#xa;информации" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_938503075" CREATED="1685027070050" MODIFIED="1685029207028" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-198.99999 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<node TEXT="Внутренние факторы" LOCALIZED_STYLE_REF="AutomaticLayout.level,3" ID="ID_1501840191" CREATED="1685027104888" MODIFIED="1685029207029" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-189.24999 pt" VSHIFT_QUANTITY="34.5 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Внешние факторы" LOCALIZED_STYLE_REF="AutomaticLayout.level,3" ID="ID_1456310898" CREATED="1685027118935" MODIFIED="1685029207029" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-180.24999 pt" VSHIFT_QUANTITY="-26.25 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
</node>
<node TEXT="Перечень субъективных факторов, воздействующих на безопасность защищаемой&#xa;информации" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" FOLDED="true" ID="ID_170453076" CREATED="1685027156969" MODIFIED="1685029207029" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-198.24999 pt" VSHIFT_QUANTITY="7.5 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<node TEXT="Внутренние факторы" LOCALIZED_STYLE_REF="AutomaticLayout.level,3" ID="ID_1877073464" CREATED="1685027190095" MODIFIED="1685027600784" ICON_SIZE="12 pt" BACKGROUND_COLOR="#333333" STYLE="narrow_hexagon" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-188.49999 pt" VSHIFT_QUANTITY="-9 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#3366ff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Внешние факторы" LOCALIZED_STYLE_REF="AutomaticLayout.level,3" ID="ID_1172062236" CREATED="1685027194550" MODIFIED="1685027480592" ICON_SIZE="12 pt" BACKGROUND_COLOR="#333333" STYLE="narrow_hexagon" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="CENTER" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-180.24999 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#3366ff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</node>
</node>
</node>
<node TEXT="Библиография" LOCALIZED_STYLE_REF="AutomaticLayout.level,1" POSITION="bottom_or_right" ID="ID_310828609" CREATED="1685027795471" MODIFIED="1685029280051" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-474.99999 pt" VSHIFT_QUANTITY="-44.25 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
<node TEXT="Рекомендации по&#xa;Р 50.1.053—2005" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_719516495" CREATED="1685027829547" MODIFIED="1685029207029" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-178.74999 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="Рекомендации по&#xa;Р 50.1.056—2005" LOCALIZED_STYLE_REF="AutomaticLayout.level,2" ID="ID_116547915" CREATED="1685027849161" MODIFIED="1685029207029" ICON_SIZE="12 pt" COLOR="#000099" BACKGROUND_COLOR="#ff6666" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="20 px" SHAPE_VERTICAL_MARGIN="20 px" NUMBERED="false" FORMAT="STANDARD_FORMAT" MAX_WIDTH="10 cm" MIN_WIDTH="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="3.1 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#2c2b29" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" HGAP_QUANTITY="-177.99999 pt" VGAP_QUANTITY="0 pt" COMMON_HGAP_QUANTITY="275.74999 pt">
<edge STYLE="bezier" COLOR="#ffffff" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</node>
</node>
</node>
</map>
